presubmits:
  maistra/maistra.github.io:
  - name: maistra.github.io_lint
    decorate: true
    always_run: true
    skip_report: false
    branches:
      - maistra-2.0
      - maistra-1.1
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - lint
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 4Gi
    trigger: "(?m)^/test lint"
    rerun_command: "/test lint"
  - name: maistra.github.io_check-links
    decorate: true
    always_run: true
    skip_report: false
    branches:
      - maistra-2.0
      - maistra-1.1
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - check-links
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 4Gi
    trigger: "(?m)^/test check-links"
    rerun_command: "/test check-links"
  maistra/istio-operator:
  - name: istio-operator_unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-2.0
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - compile
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        - name: TEST_FLAGS
          value: -v
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
  - name: istio-operator_gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-2.0
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - gen-check
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
  - name: istio-operator_release
    decorate: true
    always_run: false
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    labels:
      preset-quay-pusher: "true"
      preset-copr: "true"
      preset-github: "true"
    branches:
      - maistra-2.0
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - release
        securityContext:
          privileged: true
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
  maistra/test-infra:
  - name: test-infra_lint
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - main
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - lint
        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
  - name: test-infra_gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - main
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - gen-check
        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
  - name: test-infra_build-containers
    decorate: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    run_if_changed: '^docker/maistra-builder_.*\.Dockerfile|^docker/scripts'
    branches:
      - main
    max_concurrency: 2
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - build-containers
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
  - name: test-infra_build-proxy-containers
    decorate: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    run_if_changed: '^docker/maistra-proxy-builder_.*\.Dockerfile'
    branches:
      - main
    max_concurrency: 2
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - build-proxy-containers
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

  maistra/proxy:
  - name: proxy_2.0-unit
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
    decorate: true
    decoration_config:
      timeout: 5h0m0s
    always_run: true
    path_alias: istio.io/proxy
    skip_report: false
    max_concurrency: 1
    branches:
      - maistra-2.0
      - jwendell/ci
    rerun_command: /test unit
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-proxy-builder:2.0"
        imagePullPolicy: Always
        command:
        - ./maistra/ci/pre-submit.sh
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
  - name: proxy_1.1-unit
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
    decorate: true
    decoration_config:
      timeout: 5h0m0s
    always_run: true
    path_alias: istio.io/proxy
    skip_report: false
    max_concurrency: 1
    branches:
      - maistra-1.1
    rerun_command: /test unit
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-proxy-builder:1.1"
        imagePullPolicy: Always
        command:
        - ./maistra/ci/pre-submit.sh
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

  maistra/envoy:
  - name: envoy_1.1-unit
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
    decorate: true
    decoration_config:
      timeout: 5h0m0s
    always_run: true
    path_alias: istio.io/envoy
    skip_report: false
    max_concurrency: 1
    branches:
      - maistra-1.1
      - jwendell/ci
    rerun_command: /test unit
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-proxy-builder:1.1"
        imagePullPolicy: Always
        command:
        - ./maistra/run-ci.sh
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
  - name: envoy_2.0-unit
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
    decorate: true
    decoration_config:
      timeout: 5h0m0s
    always_run: true
    path_alias: istio.io/envoy
    skip_report: false
    max_concurrency: 1
    branches:
      - maistra-2.0
    rerun_command: /test unit
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-proxy-builder:2.0"
        imagePullPolicy: Always
        command:
        - ./maistra/run-ci.sh
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

  maistra/istio:
  - name: istio_2.0-unit
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    max_concurrency: 2
    branches:
      - maistra-2.0
    rerun_command: /test unit
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - -e
        - T=-v
        - build
        - racetest
        - binaries-test
        env:
        - name: BUILD_WITH_CONTAINER
          value: "0"
        - name: GOFLAGS
          value: -mod=vendor
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        - name: ISTIO_ENVOY_BASE_URL
          value: https://storage.googleapis.com/maistra-prow-testing/proxy
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

  - name: istio_2.0-lint
    trigger: (?m)^/test( | .* )lint,?($|\s.*)
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    max_concurrency: 2
    branches:
      - maistra-2.0
    rerun_command: /test lint
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:2.0"
        imagePullPolicy: Always
        command:
        - make
        - lint
        env:
        - name: BUILD_WITH_CONTAINER
          value: "0"
        - name: GOFLAGS
          value: -mod=vendor
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        - name: ISTIO_ENVOY_BASE_URL
          value: https://storage.googleapis.com/maistra-prow-testing/proxy
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

  - name: istio_2.0-gencheck
    trigger: (?m)^/test( | .* )gencheck,?($|\s.*)
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    max_concurrency: 2
    branches:
      - maistra-2.0
    rerun_command: /test gencheck
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:2.0"
        imagePullPolicy: Always
        command:
        - make
        - maistra-gen-k8s-client
        - gen-check
        env:
        - name: BUILD_WITH_CONTAINER
          value: "0"
        - name: GOFLAGS
          value: -mod=vendor
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        - name: ISTIO_ENVOY_BASE_URL
          value: https://storage.googleapis.com/maistra-prow-testing/proxy
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

  - name: istio_2.0-integration
    trigger: (?m)^/test( | .* )integration,?($|\s.*)
    rerun_command: /test integration
    skip_report: false
    max_concurrency: 2
    always_run: true
    branches:
    - maistra-2.0
    decorate: true
    path_alias: istio.io/istio
    spec:
      containers:
      - command:
        - entrypoint
        - prow/integ-suite-kind.sh
        - test.integration.kube.presubmit
        env:
        - name: GOFLAGS
          value: -mod=vendor
        - name: BUILD_WITH_CONTAINER
          value: "0"
        - name: ISTIO_ENVOY_BASE_URL
          value: https://storage.googleapis.com/maistra-prow-testing/proxy
        image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup

  - name: istio_1.1-unit
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - -e
        - T=-v
        - init
        - test
        env:
        - name: GOFLAGS
          value: -mod=vendor
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

  - name: istio_1.1-integration
    skip_report: false
    max_concurrency: 2
    always_run: true
    branches:
    - maistra-1.1
    decorate: true
    path_alias: istio.io/istio
    spec:
      containers:
      - command:
        - entrypoint
        - prow/integ-suite-kind.sh
        - test.integration.kube.presubmit
        env:
        - name: GOFLAGS
          value: -mod=vendor
        - name: BUILD_WITH_CONTAINER
          value: "0"
        image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup

  maistra/rpm-common:
  - name: rpm-common_tests
    decorate: true
    always_run: true
    path_alias: maistra.io/rpm-common
    skip_report: false
    branches:
      - maistra-2.0
      # Allow for testing
      - playground
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - test
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi

  maistra/rpm-ior:
  - name: rpm-ior_tests
    decorate: true
    always_run: true
    path_alias: maistra.io/rpm-ior
    skip_report: false
    branches:
      - maistra-2.0
      # Allow for testing
      - playground
    labels:
      preset-copr: "true"
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - test
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi

  maistra/rpm-istio-operator:
  - name: rpm-istio-operator_tests
    decorate: true
    always_run: true
    path_alias: maistra.io/rpm-istio-operator
    skip_report: false
    branches:
      - maistra-2.0
      # Allow for testing
      - playground
    labels:
      preset-copr: "true"
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - make
        - test
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi

  maistra/header-append-filter:
  - name: header-append-filter_build-containers
    decorate: true
    path_alias: github.com/maistra/header-append-filter
    skip_report: false
    always_run: true
    branches:
      - main
    max_concurrency: 2
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:2.0"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - container
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi

## The presubmits below are for the maistra-prow-testing org, which is our test bed
  maistra-prow-testing/test-infra:
  - name: build-containers
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - main
    max_concurrency: 1
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.2"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - maistra-builder
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
  maistra-prow-testing/istio-operator:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-2.0
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 2Gi
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
      - maistra-2.0
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.1"
        imagePullPolicy: Always
        command:
        - make
        - gen-check
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
  maistra-prow-testing/istio:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.0"
        imagePullPolicy: Always
        command:
        - make
        - init
        - test
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
  - name: integrationtests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:1.0"
        imagePullPolicy: Always
        command:
        - make
        - init
        - test.integration.local
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
