presubmits:
  maistra/test-infra:
  - name: test-infra_lint
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - main
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:2.3"
        imagePullPolicy: Always
        command:
        - make
        - lint
        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
  - name: test-infra_gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/test-infra
    skip_report: false
    branches:
      - main
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:2.3"
        imagePullPolicy: Always
        command:
        - make
        - gen-check
        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi

  maistra/proxy:
  - name: proxy-unit-2.1
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
    decorate: true
    decoration_config:
      timeout: 8h0m0s
    always_run: true
    path_alias: istio.io/proxy
    skip_report: false
    max_concurrency: 1
    branches:
      - ^maistra-2.1$
    rerun_command: /test unit
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-proxy-builder:2.1"
        imagePullPolicy: Always
        command:
        - ./maistra/ci/pre-submit.sh
        env:
        - name: BAZEL_REMOTE_CACHE
          value: http://bazel-cache.default/cache
        resources:
          limits:
            memory: 16Gi
            cpu: "8"
          requests:
            cpu: "4"
            memory: 4Gi

  maistra/envoy:
  - name: envoy-unit-2.1
    trigger: (?m)^/test( | .* )unit,?($|\s.*)
    decorate: true
    decoration_config:
      timeout: 8h0m0s
    always_run: true
    path_alias: istio.io/envoy
    skip_report: false
    max_concurrency: 1
    branches:
      - ^maistra-2.1$
    rerun_command: /test unit
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-proxy-builder:2.1"
        imagePullPolicy: Always
        command:
        - ./maistra/run-ci.sh
        env:
        - name: BAZEL_REMOTE_CACHE
          value: http://bazel-cache.default/cache
        resources:
          limits:
            memory: 16Gi
            cpu: "8"
          requests:
            cpu: "4"
            memory: 4Gi

  maistra/istio:
  - name: istio-integration-2.1
    trigger: (?m)^/test( | .* )integration,?($|\s.*)
    rerun_command: /test integration
    skip_report: false
    max_concurrency: 2
    always_run: true
    branches:
    - ^maistra-2.1$
    decorate: true
    path_alias: istio.io/istio
    spec:
      containers:
      - command:
        - entrypoint
        - prow/integ-suite-kind.sh
        - test.integration.kube.presubmit
        env:
        - name: GOFLAGS
          value: -mod=vendor
        - name: BUILD_WITH_CONTAINER
          value: "0"
        - name: ISTIO_ENVOY_BASE_URL
          value: https://storage.googleapis.com/maistra-prow-testing/proxy
        image: "quay.io/maistra-dev/maistra-builder:2.1"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup
  - name: istio-integration-maistra-mc-2.1
    trigger: (?m)^/test( | .* )integration\-maistra\-mc,?($|\s.*)
    rerun_command: /test integration-maistra-mc
    skip_report: false
    max_concurrency: 2
    always_run: true
    branches:
    - ^maistra-2.1$
    decorate: true
    path_alias: istio.io/istio
    spec:
      containers:
      - command:
        - entrypoint
        - prow/integ-suite-kind.sh
        - --topology
        - MULTICLUSTER
        - test.integration.servicemesh.kube
        env:
        - name: GOFLAGS
          value: -mod=vendor
        - name: BUILD_WITH_CONTAINER
          value: "0"
        - name: ISTIO_ENVOY_BASE_URL
          value: https://storage.googleapis.com/maistra-prow-testing/proxy
        - name: TEST_SELECT
          value: -postsubmit,-flaky,+multicluster
        image: "quay.io/maistra-dev/maistra-builder:2.1"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
          requests:
            cpu: "4"
            memory: 4Gi
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
      - hostPath:
          path: /sys/fs/cgroup
          type: Directory
        name: cgroup

  maistra/header-append-filter:
  - name: header-append-filter_build-containers
    decorate: true
    path_alias: github.com/maistra/header-append-filter
    skip_report: false
    always_run: true
    branches:
      - ^maistra-2.4$
      - ^maistra-2.3$
      - ^maistra-2.2$
    max_concurrency: 2
    spec:
      containers:
      - image: "quay.io/maistra-dev/maistra-builder:2.4"
        imagePullPolicy: Always
        command:
        - entrypoint
        - make
        - container
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/docker
          name: varlibdocker
          readOnly: false
        resources:
          limits:
            memory: 16Gi
            cpu: "4"
          requests:
            cpu: "2"
            memory: 2Gi
      volumes:
      - emptyDir: {}
        name: varlibdocker
