github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

tide:
  merge_method:
    maistra: squash
  target_url: https://prow.maistra.io/tide

  queries:

  - repos:
    - maistra/rpm-common
    - maistra/rpm-ior
    - maistra/rpm-istio-operator
    - maistra/test-infra
    - maistra/proxy
    - maistra/envoy
    labels:
    - "okay to merge"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    reviewApprovedRequired: true

  - repos:
    - maistra/rpm-ior
    - maistra/rpm-istio-operator
    - maistra/proxy
    - maistra/test-infra
    author: maistra-bot
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    labels:
    - auto-merge
    reviewApprovedRequired: false
