github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

tide:
  blocker_label: merge-blocker
  rebase_label: "don't squash"
  merge_label: "merge strategy"
  merge_method:
    maistra: squash
    dgn: squash
  target_url: https://prow.maistra.io/tide
  context_options:
    from-branch-protection: true
    # Treat unknown contexts as optional
    skip-unknown-contexts: true

  queries:

  - repos:
    - maistra/test-infra
    - maistra/olm-metadata
    - maistra/maistra.github.io
    - maistra/istio-cni
    - maistra/rpms
    - maistra/ior
    - maistra/jwt_verify_lib
    - dgn/oidc-filter
    labels:
    - "okay to merge"
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    reviewApprovedRequired: true
