branch-protection:
  allow_disabled_policies: true
  protect: false
  orgs:
    maistra-prow-testing:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: false
    Maistra:
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: false
deck:
  spyglass:
    size_limit: 500000000  # 500 MB
    lenses:
    - lens:
        name: buildlog
        config:
          highlight_regexes:
          - timed out
          - 'ERROR:'
          - (FAIL|Failure \[)\b
          - panic\b
          - ^E\d{4} \d\d:\d\d:\d\d\.\d\d\d]
      required_files:
      - build-log.txt
    - lens:
        name: junit
      required_files:
      - artifacts/junit.*\.xml
plank:
  job_url_prefix_config:
    '*': "https://prow.maistra.io/view/gcs/"
  default_decoration_configs:
    '*':
      timeout: 2h
      grace_period: 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200117-c08038c1c"
        initupload: "gcr.io/k8s-prow/initupload:v20200117-c08038c1c"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200117-c08038c1c"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200117-c08038c1c"
      gcs_configuration:
        path_strategy: explicit
        bucket: "maistra-prow-testing"
      gcs_credentials_secret: "gcs-credentials"
presubmits:
  Maistra/istio-operator:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  
## The presubmits below are for the maistra-prow-testing org, which is our test bed
  maistra-prow-testing/istio-operator:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - test
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: gen-check
    decorate: true
    always_run: true
    path_alias: github.com/maistra/istio-operator
    skip_report: false
    branches:
      - maistra-1.1
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.1"
        command:
        - make
        - gen-check
        env:
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  maistra-prow-testing/istio:
  - name: unittests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.0"
        command:
        - make
        - init
        - test
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
  - name: integrationtests
    decorate: true
    always_run: true
    path_alias: istio.io/istio
    skip_report: false
    branches:
      - maistra-1.0
    spec:
      containers:
      - image: "registry.gitlab.com/dgrimm/istio/maistra-builder:1.0"
        command:
        - make
        - init
        - test.integration.local
        env:
        - name: ISTIO_BUILD_BUCKET
          value: "maistra-prow-testing"
        - name: XDG_CACHE_HOME
          value: /tmp/cache
        - name: GOCACHE
          value: /tmp/cache
prowjob_namespace: default
pod_namespace: test-pods
sinker:
  resync_period: 1h
  max_prowjob_age: 168h
  max_pod_age: 6h
# tide:
#   merge_method:
#     maistra-prow-testing: squash
#   target_url: https://prow.maistra.io/tide
#   queries:
#   - orgs:
#     - maistra-prow-testing
#     labels:
#     - okay to merge
#     missingLabels:
#     - do-not-merge
#     - do-not-merge/hold
#     - do-not-merge/work-in-progress
#     - do-not-merge/invalid-owners-file
#     - needs-rebase
#   context_options:
#     from-branch-protection: true
#     skip-unknown-contexts: true
#     orgs:
#       maistra-prow-testing:
#         repos:
#           istio:
#             required-contexts:
#             - "unittests"
#             - "integrationtests"
